sudo: required
services:
  - docker

before_install:
  - docker build -t anrybalova/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true anrybalova/docker-react npm run test -- --coverage

deploy:
  edge: true
  provider: elasticbeanstaslk
  region: "us-east-2"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-2-602096333847"
  bucket_path: "docker-react"
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  on:
    branch: master
