sudo: required
services:
  - docker

before_install:
  - docker build -t anrybalova/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true anrybalova/docker-react npm run test -- --coverage
